language: cpp
dist: trusty
sudo: required
os: linux

compiler:
    - gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTS=ON ..

script:
    - make -j4
    - ./runtests
