language: cpp
dist: trusty
sudo: required
os: linux

before_install:
    - sudo apt-get update
    - sudo apt-get upgrade

compiler:
    - gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make -j4
    - make test
